---
- name: Import SSL Keys
  bigip_ssl_key:
    name: "{{ item }}"
    content: "{{ lookup('file', '{{ keys_path }}/{{ item }}') }}"
    provider: "{{ provider }}"
  loop: "{{ keys }}"
  notify: "config has changed"
  when: keys is defined

- name: Import SSL Certs
  bigip_ssl_certificate:
    name: "{{ item }}"
    content: "{{ lookup('file', '{{ certs_path }}/{{ item }}') }}"
    provider: "{{ provider }}"
  loop: "{{ certs }}"
  notify: "config has changed"
  when: certs is defined