---
- name: Perform a config sync
  bigip_configsync_action:
    device_group: "{{ device_group.name }}"
    sync_device_to_group: yes
    provider: "{{ provider }}"
  listen: "config has changed"
  when: "'active' in failoverStatus['stdout'][0]"

- name: Save the running configuration of the BIG-IP
  bigip_config:
    save: yes
    provider: "{{ provider }}"
  listen: "config has changed"