---

ansible_host: 10.144.11.41


nets:
  - name: Self-Internal
    address: 10.144.22.41
    netmask: 255.255.255.0
    vlan:
      name: Internal
      interfaces:
        - 1.1
  - name: Self-External
    address: 10.144.12.41
    netmask: 255.255.255.0
    vlan:
      name: External
      interfaces:
        - 1.2
  - name: Self-HA
    address: 10.144.21.41
    netmask: 255.255.255.0
    vlan:
      name: HA
      interfaces:
        - 1.3

config_sync_ip: 10.144.21.41
mirror_primary_address: 10.144.21.41
unicast_failover:
  - address: 10.144.21.41