---

ansible_host: 10.144.11.42

nets:
  - name: Self-Internal
    address: 10.144.22.42
    netmask: 255.255.255.0
    vlan:
      name: Internal
      interfaces:
        - 1.1
  - name: Self-External
    address: 10.144.12.42
    netmask: 255.255.255.0
    vlan:
      name: External
      interfaces:
        - 1.2
  - name: Self-HA
    address: 10.144.21.42
    netmask: 255.255.255.0
    vlan:
      name: HA
      interfaces:
        - 1.3

config_sync_ip: 10.144.21.42
mirror_primary_address: 10.144.21.42
unicast_failover:
  - address: 10.144.21.42